// Code generated by Wire. DO NOT EDIT.
// (Hand-written; re-run `wire` to regenerate from wire.go)

//go:build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	"github.com/opscenter/ai-gateway/internal/biz"
	"github.com/opscenter/ai-gateway/internal/conf"
	"github.com/opscenter/ai-gateway/internal/data"
	"github.com/opscenter/ai-gateway/internal/observability"
	"github.com/opscenter/ai-gateway/internal/server"
	"github.com/opscenter/ai-gateway/internal/service"
)

// Injectors from wire.go:

func wireApp(bc *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDB(bc.Database, logger)
	if err != nil {
		return nil, nil, err
	}

	rdb, err := data.NewRedis(bc.Redis, logger)
	if err != nil {
		return nil, nil, err
	}

	_, cleanup, err := data.NewData(db, rdb, logger)
	if err != nil {
		return nil, nil, err
	}

	metrics := observability.NewMetrics()

	// ES client is optional; pass nil to use Redis spill queue when ES is unavailable.
	auditWorker := biz.NewAuditWorker(db, rdb, nil, bc.Audit, bc.System, logger)
	quotaManager := biz.NewQuotaManager(rdb, db, logger)
	routerManager := biz.NewRouterManager(rdb, db, metrics, logger)
	billingManager := biz.NewBillingManager(db, rdb, metrics, bc.System, logger)
	gatewayUseCase := biz.NewGatewayUseCase(db, rdb, quotaManager, auditWorker, routerManager, billingManager, metrics, bc.AI, bc.System, logger)
	authUseCase := biz.NewAuthUseCase(db, bc.Auth, bc.System, logger)

	gatewayService := service.NewGatewayService(gatewayUseCase, billingManager)
	authService := service.NewAuthService(authUseCase)

	readyChecker := server.NewReadyChecker(db, rdb)
	httpSrv := server.NewHTTPServer(bc.Server, bc.System, gatewayService, authService, authUseCase, gatewayUseCase, quotaManager, readyChecker, logger)
	kratosServer := server.NewKratosServer(bc.Server, httpSrv, metrics, readyChecker, auditWorker, gatewayUseCase, logger)

	app := newApp(logger, kratosServer)
	return app, cleanup, nil
}

// Provider functions referenced by wire.go declarations (used only by the wire tool).

func provideDatabase(bc *conf.Bootstrap) *conf.Database { return bc.Database }
func provideRedis(bc *conf.Bootstrap) *conf.Redis       { return bc.Redis }
func provideAI(bc *conf.Bootstrap) *conf.AI             { return bc.AI }
func provideSystem(bc *conf.Bootstrap) *conf.System     { return bc.System }
func provideServer(bc *conf.Bootstrap) *conf.Server     { return bc.Server }
func provideAuth(bc *conf.Bootstrap) *conf.Auth         { return bc.Auth }
func provideAudit(bc *conf.Bootstrap) *conf.Audit       { return bc.Audit }
