// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.4
// source: api/guardrail/v1/guardrail.proto

package guardrailv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// text is the decoded IR message text (not raw JSON) — same content shape
	// the built-in pii_rules checker inspects.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// direction is "inbound" or "outbound" (guardrail.Direction).
	Direction  string `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	TenantName string `protobuf:"bytes,3,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	// checker_name lets one engine serve multiple configured checker instances
	// (e.g. distinct policies) differently if it chooses to.
	CheckerName   string `protobuf:"bytes,4,opt,name=checker_name,json=checkerName,proto3" json:"checker_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_api_guardrail_v1_guardrail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_guardrail_v1_guardrail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_api_guardrail_v1_guardrail_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CheckRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *CheckRequest) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *CheckRequest) GetCheckerName() string {
	if x != nil {
		return x.CheckerName
	}
	return ""
}

type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// action is "none" | "log" | "redact" | "block" (guardrail.Action).
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// types are finding categories for audit (e.g. "person_name", "address").
	Types []string `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	// redacted_text is populated when action == "redact".
	RedactedText  string `protobuf:"bytes,3,opt,name=redacted_text,json=redactedText,proto3" json:"redacted_text,omitempty"`
	Details       string `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_api_guardrail_v1_guardrail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_guardrail_v1_guardrail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_api_guardrail_v1_guardrail_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckResponse) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *CheckResponse) GetRedactedText() string {
	if x != nil {
		return x.RedactedText
	}
	return ""
}

func (x *CheckResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_api_guardrail_v1_guardrail_proto protoreflect.FileDescriptor

var file_api_guardrail_v1_guardrail_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x75, 0x61, 0x72, 0x64, 0x72, 0x61, 0x69, 0x6c, 0x2f,
	0x76, 0x31, 0x2f, 0x67, 0x75, 0x61, 0x72, 0x64, 0x72, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x67, 0x75, 0x61, 0x72, 0x64, 0x72, 0x61, 0x69, 0x6c, 0x2e, 0x76, 0x31,
	0x22, 0x84, 0x01, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7c, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x64, 0x61, 0x63, 0x74,
	0x65, 0x64, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x54, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x32, 0x53, 0x0a, 0x0f, 0x47, 0x75, 0x61, 0x72, 0x64, 0x72, 0x61,
	0x69, 0x6c, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x40, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x12, 0x1a, 0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x72, 0x61, 0x69, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x67, 0x75, 0x61, 0x72, 0x64, 0x72, 0x61, 0x69, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x73, 0x63, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x2f, 0x61, 0x69, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x67, 0x75, 0x61, 0x72, 0x64, 0x72, 0x61, 0x69, 0x6c, 0x2f, 0x76, 0x31, 0x3b, 0x67,
	0x75, 0x61, 0x72, 0x64, 0x72, 0x61, 0x69, 0x6c, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_api_guardrail_v1_guardrail_proto_rawDescOnce sync.Once
	file_api_guardrail_v1_guardrail_proto_rawDescData []byte
)

func file_api_guardrail_v1_guardrail_proto_rawDescGZIP() []byte {
	file_api_guardrail_v1_guardrail_proto_rawDescOnce.Do(func() {
		file_api_guardrail_v1_guardrail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_guardrail_v1_guardrail_proto_rawDesc), len(file_api_guardrail_v1_guardrail_proto_rawDesc)))
	})
	return file_api_guardrail_v1_guardrail_proto_rawDescData
}

var file_api_guardrail_v1_guardrail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_guardrail_v1_guardrail_proto_goTypes = []any{
	(*CheckRequest)(nil),  // 0: guardrail.v1.CheckRequest
	(*CheckResponse)(nil), // 1: guardrail.v1.CheckResponse
}
var file_api_guardrail_v1_guardrail_proto_depIdxs = []int32{
	0, // 0: guardrail.v1.GuardrailEngine.Check:input_type -> guardrail.v1.CheckRequest
	1, // 1: guardrail.v1.GuardrailEngine.Check:output_type -> guardrail.v1.CheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_guardrail_v1_guardrail_proto_init() }
func file_api_guardrail_v1_guardrail_proto_init() {
	if File_api_guardrail_v1_guardrail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_guardrail_v1_guardrail_proto_rawDesc), len(file_api_guardrail_v1_guardrail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_guardrail_v1_guardrail_proto_goTypes,
		DependencyIndexes: file_api_guardrail_v1_guardrail_proto_depIdxs,
		MessageInfos:      file_api_guardrail_v1_guardrail_proto_msgTypes,
	}.Build()
	File_api_guardrail_v1_guardrail_proto = out.File
	file_api_guardrail_v1_guardrail_proto_goTypes = nil
	file_api_guardrail_v1_guardrail_proto_depIdxs = nil
}
