// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: api/guardrail/v1/guardrail.proto

package guardrailv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GuardrailEngine_Check_FullMethodName = "/guardrail.v1.GuardrailEngine/Check"
)

// GuardrailEngineClient is the client API for GuardrailEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GuardrailEngine is the contract an operator's external detection service
// implements (docs/design/06-security-and-guardrails.md, P2 "external"
// checker) — Microsoft Presidio, a cloud DLP API, or an in-house engine, all
// behind this one RPC. The gateway is the client; this repo does not ship a
// server implementation.
type GuardrailEngineClient interface {
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type guardrailEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewGuardrailEngineClient(cc grpc.ClientConnInterface) GuardrailEngineClient {
	return &guardrailEngineClient{cc}
}

func (c *guardrailEngineClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, GuardrailEngine_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuardrailEngineServer is the server API for GuardrailEngine service.
// All implementations must embed UnimplementedGuardrailEngineServer
// for forward compatibility.
//
// GuardrailEngine is the contract an operator's external detection service
// implements (docs/design/06-security-and-guardrails.md, P2 "external"
// checker) — Microsoft Presidio, a cloud DLP API, or an in-house engine, all
// behind this one RPC. The gateway is the client; this repo does not ship a
// server implementation.
type GuardrailEngineServer interface {
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	mustEmbedUnimplementedGuardrailEngineServer()
}

// UnimplementedGuardrailEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuardrailEngineServer struct{}

func (UnimplementedGuardrailEngineServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedGuardrailEngineServer) mustEmbedUnimplementedGuardrailEngineServer() {}
func (UnimplementedGuardrailEngineServer) testEmbeddedByValue()                         {}

// UnsafeGuardrailEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuardrailEngineServer will
// result in compilation errors.
type UnsafeGuardrailEngineServer interface {
	mustEmbedUnimplementedGuardrailEngineServer()
}

func RegisterGuardrailEngineServer(s grpc.ServiceRegistrar, srv GuardrailEngineServer) {
	// If the following call pancis, it indicates UnimplementedGuardrailEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuardrailEngine_ServiceDesc, srv)
}

func _GuardrailEngine_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardrailEngineServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardrailEngine_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardrailEngineServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuardrailEngine_ServiceDesc is the grpc.ServiceDesc for GuardrailEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuardrailEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "guardrail.v1.GuardrailEngine",
	HandlerType: (*GuardrailEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _GuardrailEngine_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/guardrail/v1/guardrail.proto",
}
